import {WALLET_CONNECT_PROJECT_ID, DEV, ALCHEMY_KEY} from '@env';

export const ENV = {
  WALLET_CONNECT_PROJECT_ID: WALLET_CONNECT_PROJECT_ID || '',
  CHAIN_IDS: DEV ? [11155111, 80001] : [1, 137],
  ALCHEMY_KEY: ALCHEMY_KEY || '',
};
