export const QUERY = {
  CONTACTS: 'CONTACTS',
  TRANSACTIONS_FROM: 'TRANSACTIONS_FROM',
  TRANSACTIONS_TO: 'TRANSACTIONS_TO',
  TOKEN_HOLDINGS: 'TOKEN_HOLDINGS',
  NATIVE_BALANCE: 'NATIVE_BALANCE',
  BALANCES: 'BALANCES',
  GAS_PRICE: 'GAS_PRICE',
};
